; PlatformIO Project Configuration File
; PPG Signal Simulator - ESP32-S3 + TFT ST7735 + MCP4725 DAC

[platformio]
default_envs = esp32_s3

[env:esp32_s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
monitor_speed = 115200
monitor_filters = 
	esp32_exception_decoder
	colorize
	time
upload_port = /dev/ttyACM0
upload_protocol = esptool
upload_speed = 115200
build_flags = 
	-DBOARD_HAS_PSRAM
	-DHARDWARE_MODEL=\"ESP32-S3\"
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=3
	-DDEBUG_ENABLED
	
	-O2
	-ffast-math
	
	-DARDUINO_LOOP_STACK_SIZE=8192
	-DCONFIG_FREERTOS_UNICORE=0
	
	; Include paths
	-I include
	-I include/data
	-I include/models
	-I include/core
	-I include/comm
	-I include/hw
	

build_src_filter = 
	+<main.cpp>
	+<models/ppg_model.cpp>
	+<core/*.cpp>
	+<hw/*.cpp>
	+<comm/*.cpp>
lib_deps = 
	olikraus/U8g2 @ ^2.36.18
	adafruit/Adafruit MCP4725@^2.0.2
	bblanchon/ArduinoJson @ ^7.0.0
